In [ ]:
import numpy as np

# Eingabematrix (AHP Vergleichsmatrix)
matrix = np.array([
    # B       T      Aw      M       A       S
    [1,     7.00,   7.00,   8.00,   8.00,   9.00],  # Baustellenmaximierung (prio = 1)
    [(1/7), 1,      1.00,   3.00,   3.00,   5.00],  # Transportdistanzminimierung (prio = 2)
    [(1/7), 1.00,   1,      3.00,   3.00,   5.00],  # Arbeitswegminimierung (prio = 2)
    [(1/8), (1/3),  (1/3),  1,      1.00,   3.00],  # Maschinenanzahlminimierung (prio = 3)
    [(1/8), (1/3),  (1/3),  1.00,   1,      3.00],  # Arbeiteranzahlminimierung (prio = 3)
    [(1/9), (1/5),  (1/5),  (1/3),  (1/3),  1   ],  # Stammfahrerverletzungsminimierung (prio = 4)
])


# 1. Normalisieren der Matrix --> Einzelne Werte durch die Spaltensumme teilen
norm_matrix = matrix / matrix.sum(axis=0)

# 2. Prioritätsvektor berechnen (Mittelwert der Zeilen der normierten Matrix)
priority_vector = norm_matrix.mean(axis=1)

# 3. Konsistenzprüfung
# Berechnung des Konsistenzindex (CI)
weighted_sum_vector = np.dot(matrix, priority_vector)
consistency_vector = weighted_sum_vector / priority_vector
lambda_max = consistency_vector.mean()
n = matrix.shape[0]
ci = (lambda_max - n) / (n - 1)

print("Konsistenzvektor:", consistency_vector)
print("Lambda Max:", lambda_max)

# Konsistenzverhältnis (CR)
# Konsistenzindex (RI) für n = 6
ri_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.9, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
ri = ri_dict[n]
cr = ci / ri

# Ergebnisse anzeigen

print("1. Normalisierte Matrix:")
print(norm_matrix)
print("\n2. Prioritätsvektor:")
print(priority_vector)
print("\n3. Konsistenzprüfung:")
print("Konsistenzindex CI:", ci)
print("Konsistenzverhältnis CR:", cr)
if cr <= 0.1:
    print("Konsistenzbedingung erfüllt (CR ≤ 0.1)")
else:
    print("Konsistenzbedingung nicht erfüllt (CR > 0.1)")

Konsistenzvektor: [6.86949776 6.36119794 6.36119794 6.05691506 6.05691506 6.15930575]
Lambda Max: 6.310838252679912
1. Normalisierte Matrix:
[[0.60722892 0.70945946 0.70945946 0.48979592 0.48979592 0.34615385]
 [0.08674699 0.10135135 0.10135135 0.18367347 0.18367347 0.19230769]
 [0.08674699 0.10135135 0.10135135 0.18367347 0.18367347 0.19230769]
 [0.07590361 0.03378378 0.03378378 0.06122449 0.06122449 0.11538462]
 [0.07590361 0.03378378 0.03378378 0.06122449 0.06122449 0.11538462]
 [0.06746988 0.02027027 0.02027027 0.02040816 0.02040816 0.03846154]]

2. Prioritätsvektor:
[0.55864892 0.14151739 0.14151739 0.0635508  0.0635508  0.03121471]

3. Konsistenzprüfung:
Konsistenzindex CI: 0.06216765053598241
Konsistenzverhältnis CR: 0.050135202045147105
Konsistenzbedingung erfüllt (CR ≤ 0.1)


In [5]:
# Manuell eingegebene AHP-Matrix
ahp_matrix = np.array([
    [1, 1/7, 1/5, 1/5],
    [7, 1, 2, 3],
    [5, 1/2, 1, 1],
    [5, 1/3, 1, 1]
])

# 1. Normalisierung der Matrix
norm_matrix = ahp_matrix / ahp_matrix.sum(axis=0)

# 2. Prioritätsvektor berechnen
priority_vector = norm_matrix.mean(axis=1)

# 3. Konsistenzprüfung
# Gewichteter Summenvektor
weighted_sum_vector = np.dot(ahp_matrix, priority_vector)
consistency_vector = weighted_sum_vector / priority_vector
lambda_max = consistency_vector.mean()
n = ahp_matrix.shape[0]
ci = (lambda_max - n) / (n - 1)

# RI-Wert für n = 4
ri_dict = {1: 0.0, 2: 0.0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24}
ri = ri_dict[n]
cr = ci / ri

# Ergebnisse anzeigen

print("1. Normalisierte Matrix:")
print(norm_matrix)
print("\n2. Prioritätsvektor:")
print(priority_vector)
print("\n3. Konsistenzprüfung:")
print("Konsistenzindex CI:", ci)
print("Konsistenzverhältnis CR:", cr)
if cr <= 0.1:
    print("Konsistenzbedingung erfüllt (CR ≤ 0.1)")
else:
    print("Konsistenzbedingung nicht erfüllt (CR > 0.1)")

1. Normalisierte Matrix:
[[0.05555556 0.07228916 0.04761905 0.03846154]
 [0.38888889 0.5060241  0.47619048 0.57692308]
 [0.27777778 0.25301205 0.23809524 0.19230769]
 [0.27777778 0.1686747  0.23809524 0.19230769]]

2. Prioritätsvektor:
[0.05348132 0.48700663 0.24029819 0.21921385]

3. Konsistenzprüfung:
Konsistenzindex CI: 0.01834743438796001
Konsistenzverhältnis CR: 0.020386038208844454
Konsistenzbedingung erfüllt (CR ≤ 0.1)
