In [20]:
import numpy as np


matrix = np.array([
    # B       S      Aw      T       M       A
    [1,      6,      6,      8,      9,     9],    # Baustellenmaximierung (prio = 1)
    [1/6,    1,      2,      3,      4,     5],    # Stammfahrerverletzungsminimierung (prio = 2)
    [1/6,    1/2,    1,      3,      3,     4],    # Arbeitswegminimierung (prio = 3)
    [1/8,    1/3,    1/3,    1,      2,     3],    # Transportdistanzminimierung (prio = 4)
    [1/9,    1/4,    1/3,    1/2,    1,     2],    # Maschinenanzahlminimierung (prio = 5)
    [1/9,    1/5,    1/4,    1/3,    1/2,   1],    # Arbeiteranzahlminimierung (prio = 6)
])



# 1. Normalisieren der Matrix --> Einzelne Werte durch die Spaltensumme teilen
norm_matrix = matrix / matrix.sum(axis=0)

# 2. Prioritätsvektor berechnen (Mittelwert der Zeilen der normierten Matrix)
priority_vector = norm_matrix.mean(axis=1)

# 3. Konsistenzprüfung
# Berechnung des Konsistenzindex (CI)
weighted_sum_vector = np.dot(matrix, priority_vector)
consistency_vector = weighted_sum_vector / priority_vector
lambda_max = consistency_vector.mean()
n = matrix.shape[0]
ci = (lambda_max - n) / (n - 1)

print("Konsistenzvektor:", consistency_vector)
print("Lambda Max:", lambda_max)

# Konsistenzverhältnis (CR)
# Konsistenzindex (RI) für n = 6
ri_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.9, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
ri = ri_dict[n]
cr = ci / ri

# Ergebnisse anzeigen

print("1. Normalisierte Matrix:")
print(norm_matrix)
print("\n2. Prioritätsvektor:")
print(priority_vector)
print("\n3. Konsistenzprüfung:")
print("Konsistenzindex CI:", ci)
print("Konsistenzverhältnis CR:", cr)
if cr <= 0.1:
    print("Konsistenzbedingung erfüllt (CR ≤ 0.1)")
else:
    print("Konsistenzbedingung nicht erfüllt (CR > 0.1)")

Konsistenzvektor: [6.74984878 6.47141614 6.29249174 6.03528315 6.07581169 6.17477404]
Lambda Max: 6.299937589420259
1. Normalisierte Matrix:
[[0.59504132 0.72434608 0.60504202 0.50526316 0.46153846 0.375     ]
 [0.09917355 0.12072435 0.20168067 0.18947368 0.20512821 0.20833333]
 [0.09917355 0.06036217 0.10084034 0.18947368 0.15384615 0.16666667]
 [0.07438017 0.04024145 0.03361345 0.06315789 0.1025641  0.125     ]
 [0.0661157  0.03018109 0.03361345 0.03157895 0.05128205 0.08333333]
 [0.0661157  0.02414487 0.02521008 0.02105263 0.02564103 0.04166667]]

2. Prioritätsvektor:
[0.54437184 0.1707523  0.12839376 0.07315951 0.04935076 0.03397183]

3. Konsistenzprüfung:
Konsistenzindex CI: 0.059987517884051836
Konsistenzverhältnis CR: 0.04837703055165471
Konsistenzbedingung erfüllt (CR ≤ 0.1)


In [21]:
# Manuell eingegebene AHP-Matrix
ahp_matrix = np.array([
    [1, 1/7, 1/5, 1/5],
    [7, 1, 2, 3],
    [5, 1/2, 1, 1],
    [5, 1/3, 1, 1]
])

# 1. Normalisierung der Matrix
norm_matrix = ahp_matrix / ahp_matrix.sum(axis=0)

# 2. Prioritätsvektor berechnen
priority_vector = norm_matrix.mean(axis=1)

# 3. Konsistenzprüfung
# Gewichteter Summenvektor
weighted_sum_vector = np.dot(ahp_matrix, priority_vector)
consistency_vector = weighted_sum_vector / priority_vector
lambda_max = consistency_vector.mean()
n = ahp_matrix.shape[0]
ci = (lambda_max - n) / (n - 1)

# RI-Wert für n = 4
ri_dict = {1: 0.0, 2: 0.0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24}
ri = ri_dict[n]
cr = ci / ri

# Ergebnisse anzeigen

print("1. Normalisierte Matrix:")
print(norm_matrix)
print("\n2. Prioritätsvektor:")
print(priority_vector)
print("\n3. Konsistenzprüfung:")
print("Konsistenzindex CI:", ci)
print("Konsistenzverhältnis CR:", cr)
if cr <= 0.1:
    print("Konsistenzbedingung erfüllt (CR ≤ 0.1)")
else:
    print("Konsistenzbedingung nicht erfüllt (CR > 0.1)")

1. Normalisierte Matrix:
[[0.05555556 0.07228916 0.04761905 0.03846154]
 [0.38888889 0.5060241  0.47619048 0.57692308]
 [0.27777778 0.25301205 0.23809524 0.19230769]
 [0.27777778 0.1686747  0.23809524 0.19230769]]

2. Prioritätsvektor:
[0.05348132 0.48700663 0.24029819 0.21921385]

3. Konsistenzprüfung:
Konsistenzindex CI: 0.01834743438796001
Konsistenzverhältnis CR: 0.020386038208844454
Konsistenzbedingung erfüllt (CR ≤ 0.1)
